export enum UserRole {
    ROLE_ADMIN = "ROLE_ADMIN",
    ROLE_LIBRARIAN = "ROLE_LIBRARIAN",
    ROLE_ASSISTANT = "ROLE_ASSISTANT",
    ROLE_STUDENT = "ROLE_STUDENT",
    ROLE_TEACHER = "ROLE_TEACHER",
  }
  