FROM postgres:14.2

ENV POSTGRES_DB=keycloak
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=password

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

USER postgres

ENTRYPOINT ["docker-entrypoint.sh"]
EXPOSE 5432
CMD ["postgres"]
