version: '3.8'

services:
  keycloak_demo:
    image: keycloak-app
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak_demo
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres_keycloak_demo 
    networks:
      - keycloak_demo_dev_network

  postgres_keycloak_demo:
    image: postgres:14.2
    command: postgres -c 'max_connections=200'
    volumes:
      - pqdata_keycloak_demo:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      PGUSER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5436:5432"
    networks:
      - keycloak_demo_dev_network

volumes:
  pqdata_keycloak_demo:

networks:
  keycloak_demo_dev_network:
    driver: bridge