version: "3.8"

services:
  keycloak_demo:
    container_name: keycloak
    hostname: ${KC_HOSTNAME}
    image: keycloak-app
    command: -v start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak_demo
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HTTP_PORT: 9080
      KEYCLOAK_FRONTEND_URL: ${KEYCLOAK_FRONTEND_URL}
      EXTRA_STARTUP_ARGS: |
        - Dkeycloak.frontendUrl=${KEYCLOAK_FRONTEND_URL}
    ports:
      - "9080:9080"
    depends_on:
      - postgres_keycloak_demo
    networks:
      - common_network
    volumes:
      - ./keycloak:/opt/keycloak/data/import

  postgres_keycloak_demo:
    image: postgres:14.2
    command: postgres -c 'max_connections=200'
    volumes:
      - pqdata_keycloak_demo:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: keycloak
      PGUSER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5436:5432"
    networks:
      - common_network

volumes:
  pqdata_keycloak_demo:

networks:
  common_network:
    name: common_network
