server:
  port: 8082


spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  application.name: backend-resources
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5000/acs_library?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: postgres
    password: toor
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  http://localhost:8080/realms/ACS_TEST

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
