#if you want to run the application with docker, you have to create the appropriate .env files
#configure according to your needs, based on the environment variables in the code
version: "3.8"

services:
  postgres:
    platform: linux/amd64
    image: postgres:14.2
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRESDB_DATABASE}
    ports:
      - "5000:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - common_network

  app:
    container_name: backend
    platform: linux/amd64
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: DockerfileBuild
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - .m2:/root/.m2
      - ./src/main/resources/static:/app/static

    stdin_open: true
    tty: true
    networks:
      - common_network

volumes:
  postgres-data:

networks:
  common_network:
    name: common_network
    external: true

